### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Sologix** [nuta/resea#54]
When I build the latest version (on Windows WSL) I get: 

        CC  kernel/boot.c
clang: error: unknown argument: '-fstack-size-section'
Makefile:250: recipe for target 'build/kernel/kernel/boot.o' failed
make: *** [build/kernel/kernel/boot.o] Error 1

**Comment by nuta** [comment]
I guess your clang is too old. Could you try building with a 10.x or newer version?

**Comment by Sologix** [comment]
I used:

`sudo apt-get install clang-10`

and then:

`sudo ln /usr/bin/clang-10 /usr/bin/clang`

This works. It compiles. But if fails at the very end:

```
  SYMBOLS  build/dm.debug.elf
     STRIP  build/dm.elf
make: llvm-objcopy: Command not found
Makefile:407: recipe for target 'build/dm.elf' failed
make: *** [build/dm.elf] Error 127

```

**Comment by nuta** [comment]
I think you haven't installed LLVM utilities. Please try installing dependencies as described in the following doc:
https://resea.org/docs/getting-started.html

**Comment by krishpranav** [comment]
curl: (28) Failed to connect to download.sourceforge.net port 443: Operation timed out
Traceback (most recent call last):
  File "/Users/apple/resea/./tools/download-file.py", line 34, in <module>
    main()
  File "/Users/apple/resea/./tools/download-file.py", line 20, in main
    subprocess.check_call(
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'curl -fsSL https://download.sourceforge.net/sourceforge/libpng/libpng-1.6.37.tar.xz -o /var/folders/q4/3cf0k68s3lq7mkh4dplm7gw40000gn/T/tmpz9mizigz/libpng-1.6.37.tar.xz' returned non-zero exit status 28.
make: *** [libs/third_party/cairo/libpng-1.6.37] Error 1

**Comment by krishpranav** [comment]
I am facing this error I am on macOS

**Comment by nuta** [comment]
It's a totally different error. Make sure if `curl -fsSL download.sourceforge.net/sourceforge/libpng/libpng-1.6.37.tar.xz | file -` succeeds.
